### ISSUE TITLE
Schools dashboard

### ISSUE THREAD

**Issue by maratomega** [ghachey/pacific-open-education-data#35]
Steps:
- Open Schools
- Open Dashboards - Enrollment by School Levels, State and Gender
- Add filter by Year - 2023
- Results are different
![image (7)](https://github.com/ghachey/pacific-open-education-data/assets/108275362/932790d9-951c-467c-a42f-4c8663b2ab68)
![image1 (1)](https://github.com/ghachey/pacific-open-education-data/assets/108275362/7c71010d-c699-4604-be35-f4cc8eef4dd2)
![image
![image3](https://github.com/ghachey/pacific-open-education-data/assets/108275362/0b5728e6-15cc-4162-81b5-715ebaa3d9a3)
2](https://github.com/ghachey/pacific-open-education-data/assets/108275362/601c5a95-ee74-4c14-99d0-a3cdc28e2d1e)
![image4](https://github.com/ghachey/pacific-open-education-data/assets/108275362/fa02f5a1-8799-4b23-9c22-4e9c812200f2)
![image5](https://github.com/ghachey/pacific-open-education-data/assets/108275362/87d7c909-9eef-43dc-8e60-cb61184d5439)

/Only the "Grand" Total results are the same

![hrthtrhrrthr](https://github.com/ghachey/pacific-open-education-data/assets/108275362/bbeff3b4-ec56-4493-84aa-cd1f97d3e0e2)

App shows `class level` data that comes from server and the web admin (looks like it) shows `school type code`, please clarify

**Comment by ghachey** [comment]
@maratomega this is because you are using the wrong data.

Do not forget that different countries have different terminologies (e.g. Districts in FSM are States, in RMI they are Atolls/Islands). Developers should refer to https://docs.pacific-emis.org/doku.php?id=emis_public_rest_api#vocab_lookup

The difference you see if because you are getting different data (actually it is the same data but disaggregated differently, this is why you get the same totals). In your first screenshot you are not actually looking at school levels. School levels is the FSM specific terminology for School Type. See the figure below. Get the School Type data using the correct API call and you will produce the exact same results.

<img width="628" alt="Screenshot 2023-10-30 114437" src="https://github.com/ghachey/pacific-open-education-data/assets/1091769/17e680ce-812b-452b-b99b-12c39263440d">

**Comment by ghachey** [comment]
@maratomega Is this understood and can it be closed?

**Comment by maratomega** [comment]
> @maratomega Is this understood and can it be closed?

Its clear now. Thank you for the clarification
